version: "1.0"
info:
  model: int-scaffold
packages:
- name: GitNewTestProject
  gitServerName: aadiacc
  gitUrl: https://github.com/aadi-tripathi
  gitUsername: aadi-tripathi
  gitBranch: main
services:
- serviceName: project.gitnewtest.integrations:daf1
  packages:
  - name: GitNewTestProject
    version: "1.0"
- serviceName: pub.date:getCurrentDate
  packages:
  - name: WmPublic
    version: 12.1.0.0.1066
